services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    command: "-jar DynamoDBLocal.jar -inMemory -sharedDb"
    working_dir: /home/dynamodblocal
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000 || exit 0"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  api:
    container_name: python
    build: ./Backend/
    restart: always
    environment:
      AWS_REGION: "eu-north-1"
      AWS_ACCESS_KEY_ID: "DUMMY_KEY"
      AWS_SECRET_ACCESS_KEY: "DUMMY_SECRET"
      SECRET_KEY: "a03143b0f89ae6552dd24a678729f3b70354b46e76a1599ef1f308e095da1069"
      DYNAMODB_ENDPOINT_URL: "http://dynamodb-local:8000"
      USERS_TABLE: "forum_users"
      CHAT_MESSAGES_TABLE: "forum_chat_messages"
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    ports:
      - 8000:8000
    volumes:
      - ./Backend:/app
    depends_on:
      dynamodb-local:
        condition: service_healthy
